branches:
  only:
    - master

environment:
  matrix:
    - RUST: stable
      BITS: 32
    - RUST: stable
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable"
  - ps: $env:RUST_VERSION = Get-Content channel-rust-stable | select -first 1 | %{$_.split('-')[1]}
  - if NOT "%RUST%" == "stable" set RUST_VERSION=%RUST%
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST_VERSION%-%ARCH%-pc-windows-gnu.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
  - ps: Start-FileDownload $Env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Gcc,Cargo,Std" /DIR="C:\Rust"
  - rustc -V
  - cargo -V

build: off

test_script:
  - echo %PATH%
  - cargo test
