[package]
name        = "cargo-audit"
description = "Audit Cargo.lock for crates with security vulnerabilities"
version     = "0.10.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/rustsec/cargo-audit"
readme      = "README.md"
categories  = ["development-tools::cargo-plugins"]
keywords    = ["cargo-subcommand", "security", "audit", "vulnerability"]
edition     = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
abscissa_core = "0.5"
gumdrop = "0.7"
home = "0.5"
lazy_static = "1"
rustsec = { version = "0.16", features = ["dependency-tree"] }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
thiserror = "1"

[dependencies.cargo-edit]
version = "= 0.4.2" # ensure `git2` dep matches when upgrading
optional = true
default-features = false
features = ["upgrade"]

[dev-dependencies]
once_cell = "1.2"
tempfile = "3"
toml = "0.5"

[dev-dependencies.abscissa_core]
version = "0.5"
features = ["testing"]

[features]
fix = ["cargo-edit"]
