[package]
name        = "cargo-audit"
description = "Audit Cargo.lock for crates with security vulnerabilities"
version     = "0.9.0-beta1"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/rustsec/cargo-audit"
readme      = "README.md"
categories  = ["development-tools"]
keywords    = ["cargo-subcommand", "security", "audit", "vulnerability"]
edition     = "2018"

[badges]
travis-ci = { repository = "rustsec/cargo-audit" }
maintenance = { status = "actively-developed" }

[dependencies]
abscissa_core = "0.3"
failure = "0.1"
gumdrop = "0.6"
home = "0.5"
lazy_static = "1"
petgraph = "0.4"
rustsec = { version = "0.13.0-alpha4", features = ["dependency-graph"] }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[dev-dependencies.abscissa_core]
version = "0.3"
features = ["testing"]
