[package]
name        = "rustsec-admin"
description = "Admin utility for maintaining the RustSec Advisory Database"
version     = "0.1.1"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/RustSec/rustsec-admin"
readme      = "README.md"
edition     = "2018"

[dependencies]
abscissa_core = "0.5"
crates_io_api = "0.5"
gumdrop = "0.7"
handlebars = "2"
rustsec = "0.17"
serde = { version = "1", features = ["serde_derive"] }
termcolor = "1"
thiserror = "1"

[dev-dependencies]
abscissa_core = { version = "0.5", features = ["testing"] }
once_cell = "1.3"
