[package]
name        = "cargo-audit"
description = "Audit Cargo.lock for crates with security vulnerabilities"
version     = "0.12.0" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/rustsec/cargo-audit"
readme      = "README.md"
categories  = ["development-tools::cargo-plugins"]
keywords    = ["cargo-subcommand", "security", "audit", "vulnerability"]
edition     = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
abscissa_core = "0.5.2"
gumdrop = "0.7"
home = "0.5"
lazy_static = "1"
rustsec = { version = "0.20", features = ["dependency-tree"] }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
once_cell = "1.4"
tempfile = "3"
toml = "0.5"

[dev-dependencies.abscissa_core]
version = "0.5"
features = ["testing"]

[features]
fix = ["rustsec/fix"]
vendored-openssl = ["rustsec/vendored-openssl"]
