[package]
name        = "rustsec"
description = "Client library for the RustSec security advisory database"
version     = "0.13.0-alpha1" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://github.com/rustsec/rustsec-crate/"
readme      = "README.md"
categories  = ["api-bindings", "development-tools"]
keywords    = ["audit", "rustsec", "security", "advisory", "vulnerability"]
edition     = "2018"

[badges]
travis-ci = { repository = "rustsec/rustsec-crate" }
maintenance = { status = "actively-developed" }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
cvss = { version = "0.3", features = ["serde"] }
git2 = "0.10"
home = "0.5"
petgraph = { version = "0.4", optional = true }
platforms = { version = "0.2", features = ["serde"] }
semver = { version = "0.9", features = ["serde"] }
semver-parser = "0.7"
serde = { version = "1", features = ["serde_derive"] }
toml = "0.5"

[dev-dependencies]
tempfile = "3"
