[package]
name = "cargo-audit"
description = "Audit Cargo.lock for crates with security vulnerabilities"
version = "0.2.0"
authors = ["Tony Arcieri <bascule@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustsec/cargo-audit"
documentation = "https://github.com/rustsec/cargo-audit"
categories = ["development-tools"]
keywords = ["cargo-subcommand", "security", "audit", "vulnerability"]

[[bin]]
name = "cargo-audit"

[dependencies]
clap = "^2"
libc = "^0.2"
rustsec = "^0.6"
semver = "^0.6"
term = "^0.4"
toml = "^0.3"
