[package]
name        = "cargo-audit"
description = "Audit Cargo.lock for crates with security vulnerabilities"
version     = "0.6.1"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/rustsec/cargo-audit"
readme      = "README.md"
categories  = ["development-tools"]
keywords    = ["cargo-subcommand", "security", "audit", "vulnerability"]
edition     = "2018"

[[bin]]
name = "cargo-audit"

[dependencies]
atty = "0.2"
gumdrop = "0.5"
gumdrop_derive = "0.5"
lazy_static = "1"
platforms = "0.2"
rustsec = "0.11"
term = "0.5"
serde_json = "1"

