[package]
name        = "rustsec"
description = "Client library for the RustSec security advisory database"
version     = "0.21.0" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/rustsec/rustsec-crate/"
readme      = "README.md"
categories  = ["api-bindings", "development-tools"]
keywords    = ["audit", "rustsec", "security", "advisory", "vulnerability"]
edition     = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
cargo-lock = { version = "4", default-features = false }
chrono = { version = "0.4", features = ["serde"] }
crates-index = { version = "0.15.2", optional = true }
cvss = { version = "1", features = ["serde"] }
git2 = { version = "0.13", optional = true }
home = { version = "0.5", optional = true }
platforms = { version = "1", features = ["serde"] }
semver = { version = "0.9", features = ["serde"] }
semver-parser = "0.9"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
toml = "0.5"

[dependencies.cargo-edit]
version = "0.6"
optional = true
default-features = false
features = ["upgrade"]

[dev-dependencies]
tempfile = "3"
once_cell = "1.3.0"

[features]
default = ["fetch"]
fetch = ["crates-index", "git2", "home"]
fix = ["cargo-edit"]
dependency-tree = ["cargo-lock/dependency-tree"]
vendored-openssl = ["git2/vendored-openssl"]

[package.metadata.docs.rs]
all-features = true
