[package]
name        = "rustsec"
description = "Client library for the RustSec security advisory database"
version     = "0.24.3" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/RustSec/rustsec/tree/main/rustsec"
readme      = "README.md"
categories  = ["api-bindings", "development-tools"]
keywords    = ["audit", "rustsec", "security", "advisory", "vulnerability"]
edition     = "2018"

[dependencies]
cargo-lock = { version = "7", default-features = false, path = "../cargo-lock" }
crates-index = { version = "0.18", optional = true }
cvss = { version = "1", features = ["serde"], path = "../cvss" }
fs-err = "2.5"
git2 = { version = "0.13", optional = true }
home = { version = "0.5", optional = true }
humantime = { version = "2", optional = true }
humantime-serde = { version = "1", optional = true }
platforms = { version = "1", features = ["serde"], path = "../platforms" }
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["serde_derive"] }
smol_str = "=0.1.17" # Pinned to avoid MSRV breakages
thiserror = "=1.0.25" # Pinned to avoid MSRV breakages
toml = "0.5"
url = { version = "2", features = ["serde"] }

[dependencies.cargo-edit]
version = "0.7"
optional = true
default-features = false
features = ["upgrade"]

[dev-dependencies]
tempfile = "3"
once_cell = "1"

[features]
default = ["git"]
fix = ["cargo-edit"]
git = ["crates-index", "git2", "home", "humantime", "humantime-serde"]
dependency-tree = ["cargo-lock/dependency-tree"]
vendored-libgit2 = ["git2/vendored-libgit2"]
vendored-openssl = ["git2/vendored-openssl"]
osv-export = ["git"]

[package.metadata.docs.rs]
all-features = true
