[advisories]
ignore = [
    # Non-utf8 String can be created with `TimeBuf::as_str`
    "RUSTSEC-2025-0140",
]

show = ["unmaintained", "unsound"]
fatal = ["critical"]

[output]
quiet = false
deny = ["warnings"]
