[package]
name        = "rustsec-admin"
description = "Admin utility for maintaining the RustSec Advisory Database"
version     = "0.8.8"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/RustSec/rustsec/tree/main/admin"
readme      = "README.md"
edition     = "2021"

[features]
default = ["gix?/max-performance-safe"]

[dependencies]
abscissa_core = "0.6"
askama = "0.11"
atom_syndication = "0.12"
chrono = { version = "0.4", default-features = false, features = ["clock"]  }
clap = "3"
comrak = { version = "0.18", default-features = false }
tame-index = { version = "0.6.0", features = ["git"] }
# NOTE: Keep in sync with `gix` used by `tame-index`.
gix = { version = "0.54", default-features = false, optional = true }
rust-embed = "6.8.1"
rustsec = { version = "0.28.0", features = ["osv-export"] }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
termcolor = "1"
thiserror = "1"
toml = "0.7"
xml-rs = "0.8"

[dev-dependencies]
abscissa_core = { version = "0.6", features = ["testing"] }
once_cell = "1.5"
